use std::env;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=cbindgen.toml");
    
    // Get build information from environment
    let out_dir = env::var("OUT_DIR").unwrap();
    let target_dir = env::var("CARGO_TARGET_DIR")
        .unwrap_or_else(|_| "target".to_string());
    let profile = env::var("PROFILE").unwrap_or_else(|_| "debug".to_string());
    
    println!("cargo:warning=Building urdf_rust with profile: {}", profile);
    
    // CMake integration: Set up library search paths
    let lib_dir = PathBuf::from(&target_dir).join(&profile);
    println!("cargo:rustc-link-search=native={}", lib_dir.display());
    
    // Link against system libraries that urdfdom depends on
    println!("cargo:rustc-link-lib=dylib=stdc++");
    
    // Set up C++ interop environment variables for CMake
    println!("cargo:rustc-env=URDF_RUST_OUT_DIR={}", out_dir);
    println!("cargo:rustc-env=URDF_RUST_TARGET_DIR={}", target_dir);
    println!("cargo:rustc-env=URDF_RUST_PROFILE={}", profile);
    
    // Generate C bindings using cbindgen
    generate_c_bindings();
    
    // Inform CMake about the Rust library location
    set_cmake_variables();
}

fn generate_c_bindings() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let output_file = PathBuf::from(&crate_dir)
        .join("include")
        .join("urdf_rust.h");
    
    // Ensure the include directory exists
    if let Some(parent) = output_file.parent() {
        std::fs::create_dir_all(parent).unwrap();
    }
    
    // For now, we'll use a manually maintained header file
    // TODO: Fix cbindgen configuration or use a different approach
    println!("cargo:warning=Using manually maintained header file at: {}", output_file.display());
    
    // Check if header file exists, if not create a minimal one
    if !output_file.exists() {
        let minimal_header = r#"
#ifndef URDF_RUST_H
#define URDF_RUST_H

#ifdef __cplusplus
extern "C" {
#endif

// Test function - will be replaced by actual URDF functions
int urdf_rust_test_function(void);

// Placeholder for future URDF parsing functions
typedef struct UrdfModel UrdfModel;

#ifdef __cplusplus
}
#endif

#endif // URDF_RUST_H
"#;
        std::fs::write(output_file, minimal_header).unwrap();
    }
}

fn set_cmake_variables() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let target_dir = env::var("CARGO_TARGET_DIR")
        .unwrap_or_else(|_| "target".to_string());
    let profile = env::var("PROFILE").unwrap_or_else(|_| "debug".to_string());
    
    // Create a CMake variable file that can be included
    let cmake_vars_file = PathBuf::from(&crate_dir)
        .join("cmake_vars.cmake");
    
    let lib_dir = PathBuf::from(&crate_dir)
        .join(&target_dir)
        .join(&profile);
    
    let cmake_content = format!(r#"
# Auto-generated CMake variables for Rust integration
# Generated by urdf_rust/build.rs

set(URDF_RUST_FOUND TRUE)
set(URDF_RUST_VERSION "5.0.2")
set(URDF_RUST_INCLUDE_DIR "{}/include")
set(URDF_RUST_LIBRARY_DIR "{}")
set(URDF_RUST_LIBRARY_NAME "urdf_rust")
set(URDF_RUST_STATIC_LIBRARY "${{URDF_RUST_LIBRARY_DIR}}/lib${{URDF_RUST_LIBRARY_NAME}}.a")

# Function to link Rust library to C++ targets
function(target_link_urdf_rust target_name)
    target_include_directories(${{target_name}} PRIVATE ${{URDF_RUST_INCLUDE_DIR}})
    target_link_libraries(${{target_name}} PRIVATE ${{URDF_RUST_STATIC_LIBRARY}})
    
    # Link required system libraries for Rust
    if(UNIX AND NOT APPLE)
        target_link_libraries(${{target_name}} PRIVATE dl pthread m)
    elseif(APPLE)
        target_link_libraries(${{target_name}} PRIVATE "-framework Security")
    endif()
endfunction()

message(STATUS "urdf_rust library configured:")
message(STATUS "  Include dir: ${{URDF_RUST_INCLUDE_DIR}}")
message(STATUS "  Library dir: ${{URDF_RUST_LIBRARY_DIR}}")
message(STATUS "  Static lib:  ${{URDF_RUST_STATIC_LIBRARY}}")
"#, 
        crate_dir.replace("\\", "/"), 
        lib_dir.display().to_string().replace("\\", "/")
    );
    
    std::fs::write(cmake_vars_file, cmake_content).unwrap();
}

// Helper function to check if we're being built by CMake
fn is_cmake_build() -> bool {
    env::var("CMAKE_BUILD_TYPE").is_ok() || 
    env::var("CMAKE_CURRENT_SOURCE_DIR").is_ok()
}

// Helper function to get the current Git commit hash for versioning
fn get_git_hash() -> String {
    let output = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output();
    
    match output {
        Ok(output) if output.status.success() => {
            String::from_utf8_lossy(&output.stdout).trim().to_string()
        }
        _ => "unknown".to_string()
    }
}